<?php
$block->pagetitleobj()->setName("plugintest");

echo $block->pagetitleobj()->getName();
echo "<br/>";
echo "testing plugins";
// echo "<h2>Non Factories Realtime Example</h2><br/>";
// echo $this->getFactorynoninjectable();
// echo "<br/>";
// echo "<h2>Factories Realtime Example</h2><br/>";
// echo $this->getvalueforfactory();


// echo "Previous topic";
// echo "<h2>Proxy RealExample</h2><br/>";
// echo $this->getValue();

